services:
  order-service:
    restart: unless-stopped
    image: com.e.bambi/order.service:1.0-SNAPSHOT
    container_name: e-bambi-order-service
    environment:
      JWT_PROVIDER_URI: http://keycloak.local:8081/realms/bambi
      DATASOURCE_URL: order-service-db:5432
      KAFKA_BOOTSTRAP_SERVERS: redpanda-0:9092,redpanda-1:9092,redpanda-2:9092
      KAFKA_SCHEMA_REGISTRY_URL: http://redpanda-0:8081
    ports:
      - "8181:8181"
    networks:
      - e-bambi-network

  inventory-service:
    restart: unless-stopped
    image: com.e.bambi/inventory.service:1.0-SNAPSHOT
    container_name: e-bambi-inventory-service
    environment:
      JWT_PROVIDER_URI: http://keycloak.local:8081/realms/bambi
      REDIS_HOST: redis-stack
      DATASOURCE_URL: inventory-service-db:5432
      KAFKA_BOOTSTRAP_SERVERS: redpanda-0:9092,redpanda-1:9092,redpanda-2:9092
      KAFKA_SCHEMA_REGISTRY_URL: http://redpanda-0:8081
    ports:
      - "8182:8182"
    networks:
      - e-bambi-network

  payment-service:
    restart: unless-stopped
    image: com.e.bambi/payment.service:1.0-SNAPSHOT
    container_name: e-bambi-payment-service
    environment:
      JWT_PROVIDER_URI: http://keycloak.local:8081/realms/bambi
      DATASOURCE_URL: payment-service-db:5432
      KAFKA_BOOTSTRAP_SERVERS: redpanda-0:9092,redpanda-1:9092,redpanda-2:9092
      KAFKA_SCHEMA_REGISTRY_URL: http://redpanda-0:8081
    ports:
      - "8183:8183"
    networks:
      - e-bambi-network