volumes:
  e-bambi-cloudbeaver:
    name: e-bambi-cloudbeaver
  e-bambi-inventory-db:
    name: e-bambi-inventory-db
  e-bambi-order-db:
    name: e-bambi-order-db
  e-bambi-payment-db:
    name: e-bambi-payment-db

services:
  cloudbeaver:
    restart: unless-stopped
    container_name: e-bambi-cloudbeaver
    image: dbeaver/cloudbeaver:25.0.0
    environment:
      - CLOUDBEAVER_EXPIRE_SESSION_AFTER_PERIOD=2147460000
    volumes:
      - e-bambi-cloudbeaver:/opt/cloudbeaver/workspace
    ports:
      - 8978:8978
    networks:
      - e-bambi-network

  inventory-service-db:
    image: postgres:14
    container_name: e-bambi-inventory-service-db
    volumes:
      - e-bambi-inventory-db:/var/lib/postgresql/data
      - ./postgres-conf/inventory/inventory-postgres.conf:/etc/postgresql/postgres.conf
      - ./postgres-conf/inventory/inventory-pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory-service
    ports:
      - "5433:5432"
    networks:
      - e-bambi-network
    command: postgres -c config_file=/etc/postgresql/postgres.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service-db:
    image: postgres:14
    container_name: e-bambi-order-service-db
    volumes:
      - e-bambi-order-db:/var/lib/postgresql/data
      - ./postgres-conf/order/order-postgres.conf:/etc/postgresql/postgres.conf
      - ./postgres-conf/order/order-pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order-service
    ports:
      - "5434:5432"
    networks:
      - e-bambi-network
    command: postgres -c config_file=/etc/postgresql/postgres.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-service-db:
    image: postgres:14
    container_name: e-bambi-payment-service-db
    volumes:
      - e-bambi-payment-db:/var/lib/postgresql/data
      - ./postgres-conf/payment/payment-postgres.conf:/etc/postgresql/postgres.conf
      - ./postgres-conf/payment/payment-pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment-service
    ports:
      - "5435:5432"
    networks:
      - e-bambi-network
    command: postgres -c config_file=/etc/postgresql/postgres.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # elasticsearch:
  #   image: elasticsearch:7.17.26
  #   container_name: e-bambi-elasticsearch
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - e-bambi-network

  # Contains Redis Stack server and RedisInsight
  # If you don't have redis-cli installed locally, you can run it from the Docker container:
  # $ docker exec -it e-bambi-redis-stack redis-cli <command> ## MONITOR
  redis-stack:
    image: redis/redis-stack:latest
    container_name: e-bambi-redis-stack
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight running on localhost:8001
    networks:
      - e-bambi-network
