services:
  init-kafka:
    image: confluentinc/cp-kafka:7.6.5
    networks:
      - e-bambi-network
    command:
      - bash
      - -c
      - |
        # block until kafka is reachable
        kafka-topics --bootstrap-server redpanda-0:9092 --list
        #
        echo -e 'Deleting kafka topics'
        kafka-topics --bootstrap-server redpanda-0:9092 --topic order.inventory.reserve --delete --if-exists
        kafka-topics --bootstrap-server redpanda-0:9092 --topic order.inventory.cancel_reservation --delete --if-exists
        kafka-topics --bootstrap-server redpanda-0:9092 --topic order.payment.validate --delete --if-exists
        kafka-topics --bootstrap-server redpanda-0:9092 --topic inventory.reserved --delete --if-exists
        kafka-topics --bootstrap-server redpanda-0:9092 --topic inventory.reservation_failed --delete --if-exists
        kafka-topics --bootstrap-server redpanda-0:9092 --topic inventory.reservation_cancelled --delete --if-exists
        kafka-topics --bootstrap-server redpanda-0:9092 --topic payment.validated --delete --if-exists
        kafka-topics --bootstrap-server redpanda-0:9092 --topic payment.validation_failed --delete --if-exists
        #
        echo -e 'Creating kafka topics'
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic order.inventory.reserve --replication-factor 3 --partitions 3
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic order.inventory.cancel_reservation --replication-factor 3 --partitions 3
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic order.payment.validate --replication-factor 3 --partitions 3
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic inventory.reserved --replication-factor 3 --partitions 3
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic inventory.reservation_failed --replication-factor 3 --partitions 3
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic inventory.reservation_cancelled --replication-factor 3 --partitions 3
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic payment.validated --replication-factor 3 --partitions 3
        kafka-topics --bootstrap-server redpanda-0:9092 --create --if-not-exists --topic payment.validation_failed --replication-factor 3 --partitions 3
        #
        echo -e 'Successfully created the following topics:'
        kafka-topics --bootstrap-server redpanda-0:9092 --list