helmDefaults:
  createNamespace: true
  # wait: true  # Es importante para garantizar que los recursos estén listos antes de finalizar
  # timeout: 300  # Timeout ajustado para evitar esperas innecesarias pero también cubrir despliegues

# helmfile lint 
# helmfile diff
# helmfile repos (opcional)
# helmfile apply --concurrency=5
# helmfile apply --skip-repos --concurrency=5
# helmfile apply --dry-run (validar despliegue)
# helmfile apply -e dev
# helmfile -l name=kube-prometheus-stack apply --concurrency=5

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

environments:
  dev:
    kubeContext: "minikube"
  prod:

---

releases:
  - name: keycloak
    namespace: auth
    chart: bitnami/keycloak
    version: "24.3.2"
    values:
      - "values/dev/keycloak.yaml"

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.12.0"
    installed: {{ eq .Environment.Name "prod" | toYaml }}
  
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: "1.16.2"
    installed: {{ eq .Environment.Name "prod" | toYaml }}
    hooks:
      - events: ["prepare"]
        command: "kubectl"
        args:
          - apply
          - -f
          - "https://github.com/cert-manager/cert-manager/releases/download/v1.16.3/cert-manager.crds.yaml"

  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: "3.12.2"
    installed: {{ eq .Environment.Name "prod" | toYaml }}

  - name: argo-cd
    namespace: gitops
    chart: argo/argo-cd
    version: "7.7.14"
    installed: {{ eq .Environment.Name "prod" | toYaml }}

  - name: kubernetes-dashboard
    namespace: monitoring
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: "7.10.0"
    installed: {{ eq .Environment.Name "prod" | toYaml }}
  
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "67.9.0"
    installed: {{ eq .Environment.Name "prod" | toYaml }}
    hooks:
      - events: ["prepare"]
        command: "kubectl"
        args:
          - apply
          - --server-side
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml"
          - -f
          - "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.79.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml"

