server:
  port: 8182

debug:
  enabled: true

logging:
  level:
    org:
      springframework: DEBUG

springdoc.swagger-ui.path: /

spring:
  profiles:
    active: native
  application:
    name: inventory-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_PROVIDER_URI:http://localhost:8081/realms/bambi}
  redis:
    host: ${REDIS_URL_HOTS:localhost}
    port: ${REDIS_URL_PORT:6379}
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_URL_HOST:localhost}:5433/inventory-service
    username: user
    password: password
  flyway:
    enabled: false
    url: jdbc:postgresql://${DATASOURCE_URL_HOTS:localhost}:5433/inventory-service
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true