{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
type: Opaque
data:
{{- range $service, $creds := .Values.secrets.credentials }}
  {{- range $key, $value := $creds }}
    {{ $key }}-{{ $service }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
